name: Deploy to Firebase Hosting on Push to Main
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DUCK_MOVIES_44A08 }}
          projectId: duck-movies-44a08git 